name: build
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  DOTNETVERSION: "8.0.x"
  APP: "I8Beef.ACInfinity"
  SOLUTION: "./src/I8Beef.ACInfinity.sln"
  BUILDOUTPUTPATH: "./src/I8Beef.ACInfinity/bin/Release/netstandard2.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNETVERSION }}

      - name: Install dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration Release --no-restore

      - name: Upload app build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP }}
          path: ${{ env.BUILDOUTPUTPATH }}
